# Generated by Django 4.2.4 on 2023-10-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bname', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=250)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
